# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

'''
Selenium IDE export
'''

class Testdemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demo(self):
    self.driver.get("https://ceshiren.com/")
    time.sleep(2)
    self.driver.set_window_size(968, 528)
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "测试答疑").click()
    time.sleep(2)
    # self.driver.find_element(By.LINK_TEXT, "使用pytest对实现po封装的selenium中，不同case页面跳转如何复用basepage的driver").click()
    # time.sleep(2)
    self.driver.execute_script("window.scrollTo(0,2246)")
  
